
enum OPS {
	STOP,
	NOP,PUSHA,
	PUSH,DUP,DROP,SWAP,STOR,RTOS,
	ADD,MUL,DIV,SUB,
	AND,OR,XOR,NZ,
	CALL,RET,JZ,
	QCALL,QRET,
	GET,SET,ALLOT,
	MOD,SHL,SHR,USHR,INVERT,NEGATE,ABS,
	LE,LT,GE,GT,EQ,NE,
	XLE,XLT,XGE,XGT,XEQ,XNE,
	ROT,OVER, UNROT, // rozwala
	VGET,VSET,RADD,
	EMIT,DOT,ECHO,
	IF,IFELSE,GOTO,
	LAMBDA,
	MIN,MAX,PICK,
	GTZ,EQZ,LTZ,
	TIMES,LOOP,FOR,RSUB,RGET,BEGIN,BREAK,CONTINUE,
	ADDI,MULI,ADDGET,ADDSET,IADDGET,IADDSET,
	LEI,LTI,GEI,GTI,EQI,NEI,
	IOGET,IOSET,
	VMINFO=255
};
