
enum OPS {
	STOP=0,
	PUSH,DUP,DROP,SWAP,STOR,RTOS,
	ADD,MUL,DIV,SUB,
	AND,OR,XOR,NZ,
	CALL,RET,JZ,
	QCALL,QRET,
	GET,SET,ALLOT,
	MOD,SHL,SHR,USHR,MIN,MAX,
	LE,LT,GE,GT,EQ,NE,
	ROT,OVER, // TODO ???
	VGET,VSET,RADD,
	EMIT,DOT,ECHO,
	IF,IFELSE,
	VMINFO=777
};
